"""
Agents API — Agent metadata, real metrics, signals, config.
Demo-mode aware: returns demo data when DEMO_MODE=true.
"""
import logging
from datetime import datetime, timezone, timedelta
from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel
from typing import Optional

from database import db
from config.demo import is_demo_mode

logger = logging.getLogger("AlphaAI.AgentsAPI")
router = APIRouter(prefix="/api/agents", tags=["Agents"])

AGENTS_COL = db["agents"]
SIGNALS_COL = db["trading_signals"]

# ═══════════════════════════════════════════
#  DEMO AGENTS
# ═══════════════════════════════════════════

DEMO_AGENTS = [
    {"id": "momentum-scanner", "name": "Momentum Scanner", "type": "technical",
     "description": "RSI + MACD crossover detection on BTC, ETH, SOL",
     "status": "active", "accuracy": 87, "signals": 48, "total_signals": 312,
     "assets": ["BTC", "ETH", "SOL"]},
    {"id": "sentiment-analyzer", "name": "Sentiment Analyzer", "type": "nlp",
     "description": "AI-powered market sentiment scoring using price momentum",
     "status": "active", "accuracy": 79, "signals": 24, "total_signals": 187,
     "assets": ["BTC", "ETH", "SOL", "AVAX"]},
    {"id": "whale-tracker", "name": "Whale Tracker", "type": "on-chain",
     "description": "Detects large volume spikes and unusual activity",
     "status": "active", "accuracy": 82, "signals": 12, "total_signals": 96,
     "assets": ["BTC", "ETH", "SOL"]},
    {"id": "volatility-engine", "name": "Volatility Engine", "type": "statistical",
     "description": "Bollinger Band compression and ATR-based breakout detection",
     "status": "active", "accuracy": 74, "signals": 18, "total_signals": 145,
     "assets": ["BTC", "ETH", "SOL", "LINK"]},
]


# ═══════════════════════════════════════════
#  LIST AGENTS
# ═══════════════════════════════════════════

@router.get("")
async def list_agents():
    """List all agents with real-time metrics."""
    demo = await is_demo_mode()
    if demo:
        return {"agents": DEMO_AGENTS, "demo_mode": True}

    agents_cursor = AGENTS_COL.find({}, {"_id": 0}).limit(20)
    agents = await agents_cursor.to_list(20)

    now = datetime.now(timezone.utc)
    day_ago = now - timedelta(hours=24)

    enriched = []
    for a in agents:
        aid = a["id"]
        # Count signals today
        today_count = await SIGNALS_COL.count_documents({
            "agent_id": aid,
            "generated_at": {"$gte": day_ago},
        })
        # Count total signals
        total_count = a.get("total_signals", 0)
        # Accuracy: ratio of profitable signals (simplified: BUY when price went up)
        profitable = await SIGNALS_COL.count_documents({
            "agent_id": aid,
            "signal_type": {"$in": ["BUY", "SELL"]},
            "confidence": {"$gte": 70},
        })
        total_actionable = await SIGNALS_COL.count_documents({
            "agent_id": aid,
            "signal_type": {"$in": ["BUY", "SELL"]},
        })
        accuracy = round(profitable / total_actionable * 100) if total_actionable > 0 else 0

        enriched.append({
            "id": aid,
            "name": a.get("name"),
            "type": a.get("type"),
            "description": a.get("description"),
            "status": a.get("status", "active"),
            "assets": a.get("assets", []),
            "signals": today_count,
            "total_signals": total_count,
            "accuracy": accuracy,
            "last_signal_at": a.get("last_signal_at"),
            "last_run_at": a.get("last_run_at"),
            "config": a.get("config", {}),
        })

    return {"agents": enriched, "demo_mode": False}


# ═══════════════════════════════════════════
#  GET AGENT SIGNALS
# ═══════════════════════════════════════════

@router.get("/{agent_id}/signals")
async def get_agent_signals(
    agent_id: str,
    limit: int = Query(default=20, le=50),
):
    """Get recent signals generated by a specific agent."""
    demo = await is_demo_mode()
    if demo:
        import random
        signals = []
        for i in range(min(limit, 8)):
            signals.append({
                "id": f"demo-{i}",
                "symbol": random.choice(["BTC", "ETH", "SOL"]),
                "signal_type": random.choice(["BUY", "SELL", "HOLD"]),
                "confidence": random.randint(55, 95),
                "price_at_signal": round(random.uniform(1000, 70000), 2),
                "analysis": "Demo signal — enable live mode for real analysis",
                "generated_at": (datetime.now(timezone.utc) - timedelta(minutes=i * 15)).isoformat(),
                "is_demo": True,
            })
        return {"signals": signals, "agent_id": agent_id, "demo_mode": True}

    signals = await SIGNALS_COL.find(
        {"agent_id": agent_id},
        {"_id": 0}
    ).sort("generated_at", -1).limit(limit).to_list(limit)

    # Serialize datetimes
    for s in signals:
        for k in ("generated_at", "expires_at"):
            if isinstance(s.get(k), datetime):
                s[k] = s[k].isoformat()

    return {"signals": signals, "agent_id": agent_id, "demo_mode": False}


# ═══════════════════════════════════════════
#  UPDATE AGENT CONFIG
# ═══════════════════════════════════════════

class AgentConfig(BaseModel):
    risk_level: Optional[str] = None
    timeframe: Optional[str] = None
    signal_frequency: Optional[str] = None
    asset: Optional[str] = None


@router.put("/{agent_id}/config")
async def update_agent_config(agent_id: str, config: AgentConfig):
    """Update agent configuration."""
    update = {}
    if config.risk_level:
        update["config.risk_level"] = config.risk_level
    if config.timeframe:
        update["config.timeframe"] = config.timeframe
    if config.signal_frequency:
        update["config.signal_frequency"] = config.signal_frequency
    if config.asset:
        update["config.asset"] = config.asset

    if not update:
        raise HTTPException(status_code=400, detail="No config fields provided")

    result = await AGENTS_COL.update_one({"id": agent_id}, {"$set": update})
    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="Agent not found")

    return {"message": "Configuration updated", "agent_id": agent_id}



# ═══════════════════════════════════════════
#  AGENT PERFORMANCE (demo-aware)
# ═══════════════════════════════════════════

@router.get("/performance")
async def get_agents_performance():
    """Aggregated performance stats for all agents. Demo-aware."""
    demo = await is_demo_mode()

    if demo:
        from services.demo_generators import generate_demo_agent_stats
        stats = generate_demo_agent_stats()
        return {"agents": stats, "mode": "demo"}

    agents = await AGENTS_COL.find({}, {"_id": 0}).limit(20).to_list(20)
    now = datetime.now(timezone.utc)
    day_ago = now - timedelta(hours=24)

    result = []
    for a in agents:
        aid = a["id"]
        today_count = await SIGNALS_COL.count_documents({
            "agent_id": aid, "generated_at": {"$gte": day_ago},
        })
        total_actionable = await SIGNALS_COL.count_documents({
            "agent_id": aid, "signal_type": {"$in": ["BUY", "SELL"]},
        })
        profitable = await SIGNALS_COL.count_documents({
            "agent_id": aid, "signal_type": {"$in": ["BUY", "SELL"]},
            "confidence": {"$gte": 70},
        })
        accuracy = round(profitable / total_actionable * 100) if total_actionable > 0 else 0

        result.append({
            "id": aid,
            "name": a.get("name"),
            "type": a.get("type"),
            "accuracy": accuracy,
            "win_rate": accuracy,
            "total_pnl": a.get("total_pnl", 0),
            "signals_today": today_count,
            "total_signals": a.get("total_signals", 0),
            "avg_confidence": a.get("avg_confidence", 0),
            "status": a.get("status", "active"),
            "is_demo": False,
        })

    return {"agents": result, "mode": "live"}
