"""add launch+intel+inbox tables

Revision ID: 33407f75b980
Revises: 7beff8b51618
Create Date: 2026-04-23 23:53:29.115734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33407f75b980'
down_revision: Union[str, Sequence[str], None] = '7beff8b51618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
