"""P4 global scale — osm/enrichment/discovery columns+tables

Revision ID: 3b8f517ad35d
Revises: 33407f75b980
Create Date: 2026-04-24 00:41:33.899922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8f517ad35d'
down_revision: Union[str, Sequence[str], None] = '33407f75b980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_intel', sa.Column('signals', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('venue_intel', sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('venue_profiles', sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
    op.add_column('venue_profiles', sa.Column('osm_id', sa.String(length=64), nullable=True))
    op.add_column('venue_profiles', sa.Column('osm_type', sa.String(length=20), nullable=True))
    op.add_column('venue_profiles', sa.Column('tags', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('venue_profiles', sa.Column('city', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_venue_profiles_city'), 'venue_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_venue_profiles_osm_id'), 'venue_profiles', ['osm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venue_profiles_osm_id'), table_name='venue_profiles')
    op.drop_index(op.f('ix_venue_profiles_city'), table_name='venue_profiles')
    op.drop_column('venue_profiles', 'city')
    op.drop_column('venue_profiles', 'tags')
    op.drop_column('venue_profiles', 'osm_type')
    op.drop_column('venue_profiles', 'osm_id')
    op.drop_column('venue_profiles', 'status')
    op.drop_column('venue_intel', 'last_enriched_at')
    op.drop_column('venue_intel', 'signals')
    # ### end Alembic commands ###
