"""add user_intel and rewards tables

Revision ID: e151932735a3
Revises: ccee13a398ed
Create Date: 2026-04-23 15:57:07.330684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e151932735a3'
down_revision: Union[str, Sequence[str], None] = 'ccee13a398ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_location_pings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_location_pings_device_id'), 'user_location_pings', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_location_pings_timestamp'), 'user_location_pings', ['timestamp'], unique=False)
    op.create_table('user_wallets',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('venue_reward_offers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('cost_credits', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_reward_offers_venue_id'), 'venue_reward_offers', ['venue_id'], unique=False)
    op.create_table('venue_vibe_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('vibe_score', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_vibe_history_timestamp'), 'venue_vibe_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_venue_vibe_history_venue_id'), 'venue_vibe_history', ['venue_id'], unique=False)
    op.create_table('venue_visits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_visits_device_id'), 'venue_visits', ['device_id'], unique=False)
    op.create_index(op.f('ix_venue_visits_timestamp'), 'venue_visits', ['timestamp'], unique=False)
    op.create_index(op.f('ix_venue_visits_venue_id'), 'venue_visits', ['venue_id'], unique=False)
    op.create_table('venue_redemptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('offer_id', sa.String(), nullable=False),
    sa.Column('cost_credits', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['venue_reward_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_redemptions_timestamp'), 'venue_redemptions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_venue_redemptions_user_id'), 'venue_redemptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_venue_redemptions_venue_id'), 'venue_redemptions', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venue_redemptions_venue_id'), table_name='venue_redemptions')
    op.drop_index(op.f('ix_venue_redemptions_user_id'), table_name='venue_redemptions')
    op.drop_index(op.f('ix_venue_redemptions_timestamp'), table_name='venue_redemptions')
    op.drop_table('venue_redemptions')
    op.drop_index(op.f('ix_venue_visits_venue_id'), table_name='venue_visits')
    op.drop_index(op.f('ix_venue_visits_timestamp'), table_name='venue_visits')
    op.drop_index(op.f('ix_venue_visits_device_id'), table_name='venue_visits')
    op.drop_table('venue_visits')
    op.drop_index(op.f('ix_venue_vibe_history_venue_id'), table_name='venue_vibe_history')
    op.drop_index(op.f('ix_venue_vibe_history_timestamp'), table_name='venue_vibe_history')
    op.drop_table('venue_vibe_history')
    op.drop_index(op.f('ix_venue_reward_offers_venue_id'), table_name='venue_reward_offers')
    op.drop_table('venue_reward_offers')
    op.drop_table('user_wallets')
    op.drop_index(op.f('ix_user_location_pings_timestamp'), table_name='user_location_pings')
    op.drop_index(op.f('ix_user_location_pings_device_id'), table_name='user_location_pings')
    op.drop_table('user_location_pings')
    # ### end Alembic commands ###
