import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const TermsOfService = () => {
  return (
    <div className="min-h-screen pt-28 pb-20 px-4" data-testid="terms-page">
      <div className="max-w-3xl mx-auto">
        <Link to="/" className="inline-flex items-center gap-2 text-zinc-500 hover:text-white text-sm mb-8 transition-colors" data-testid="terms-back-link">
          <ArrowLeft className="w-4 h-4" />Back to Home
        </Link>

        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>
          <h1 className="text-3xl md:text-4xl font-bold font-['Outfit'] mb-2" data-testid="terms-title">Terms of Service</h1>
          <p className="text-zinc-500 text-sm mb-10">Last updated: April 4, 2026</p>

          <div className="space-y-8 text-zinc-400 text-sm leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-white mb-3 font-['Outfit']">1. Acceptance of Terms</h2>
              <p>By accessing or using My-AlphaAI ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Platform.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3 font-['Outfit']">2. Description of Service</h2>
              <p>My-AlphaAI is a software-as-a-service platform that provides AI-generated cryptocurrency trading signals, strategy analysis tools, backtesting engines, and performance metrics. The Platform is for informational and educational purposes only.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3 font-['Outfit']">3. No Financial Advice</h2>
              <p>Nothing on the Platform constitutes financial, investment, legal, or tax advice. All trading signals, strategy suggestions, and performance data are generated by algorithmic models and should not be interpreted as a recommendation to buy, sell, or hold any financial instrument. You are solely responsible for your own trading decisions.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3 font-['Outfit']">4. Risk Disclosure</h2>
              <p>Cryptocurrency trading involves substantial risk of loss and is not suitable for every individual. Past performance of any strategy or signal does not guarantee future results. Simulated or backtested results may not reflect actual market conditions. You should only trade with funds you can afford to lose.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3 font-['Outfit']">5. Account Registration</h2>
              <p>To access certain features, you must create an account with a valid email and password. You are responsible for maintaining the confidentiality of your credentials and for all activities under your account.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3 font-['Outfit']">6. Subscriptions & Billing</h2>
              <p>Paid subscriptions are billed on a recurring basis (monthly). You may cancel at any time through the Billing Portal. Cancellation takes effect at the end of the current billing period. Refunds are handled on a case-by-case basis.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3 font-['Outfit']">7. Prohibited Use</h2>
              <p>You agree not to: (a) use the Platform for any unlawful purpose; (b) attempt to reverse-engineer, scrape, or copy signal data for redistribution; (c) create multiple accounts to exploit free-tier limits; (d) interfere with the operation or security of the Platform.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3 font-['Outfit']">8. Intellectual Property</h2>
              <p>All content, algorithms, code, design, and branding on the Platform are the intellectual property of My-AlphaAI and its creator. You may not reproduce, distribute, or create derivative works without written permission.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3 font-['Outfit']">9. Limitation of Liability</h2>
              <p>To the maximum extent permitted by law, My-AlphaAI and its operators shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the Platform, including but not limited to trading losses, data loss, or service interruptions.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3 font-['Outfit']">10. Modifications</h2>
              <p>We reserve the right to modify these Terms at any time. Changes will be posted on this page with an updated date. Continued use of the Platform after changes constitutes acceptance.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3 font-['Outfit']">11. Contact</h2>
              <p>For questions about these Terms, contact us at <span className="text-[#7B61FF]">support@my-alpha-ai.com</span>.</p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default TermsOfService;
